/*
 * Loan Calculator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"encoding/json"
	"errors"
	"io/ioutil"
	"log"
	"net/http"
	"strconv"
)

func CalculateLoan(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	requestBodyBytes, err := ioutil.ReadAll(r.Body)
	if err != nil {
		handleError(&w, http.StatusBadRequest, err)
		return
	}

	if len(requestBodyBytes) == 0 {
		handleError(&w, http.StatusBadRequest, errors.New("RequestBodyEmpty : Please enter request body"))
		return
	}

	var calculateloanBody CalculateloanBody
	err = json.Unmarshal(requestBodyBytes, &calculateloanBody)

	if err != nil {
		handleError(&w, http.StatusBadRequest, err)
		return
	}

	loanRepayment, err := CalculateLoanRepayments(calculateloanBody)

	if err != nil {
		handleError(&w, http.StatusInternalServerError, err)
		return
	}

	j, err := json.Marshal(&loanRepayment)
	if err != nil {
		handleError(&w, http.StatusInternalServerError, err)
		return
	}
	_, err = w.Write(j)
	if err != nil {
		handleError(&w, http.StatusInternalServerError, err)
		return
	}

	w.WriteHeader(http.StatusOK)
}

func handleError(w *http.ResponseWriter, errorCode int, er error) ModelError {
	var modelError = ModelError{Code: strconv.Itoa(errorCode), Message: er.Error()}
	modelErrorBytes, err := json.Marshal(&modelError)
	if err == nil {
		_, e := (*w).Write(modelErrorBytes)

		if e != nil {
			log.Fatal(e.Error())
		}

		(*w).WriteHeader(errorCode)

	}
	return modelError
}
