/*
 * Loan Calculator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LoanRepaymentsAmountOwing struct {
	Year      int32   `json:"year"`
	Principal float64 `json:"principal,omitempty"`
	Interest  float64 `json:"interest"`
	Total     float64 `json:"total,omitempty"`
}
