/*
 * Loan Calculator
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LoanRepayments struct {
	MonthlyRepayments float64 `json:"monthly_repayments,omitempty"`

	TotalInterestPayable float64 `json:"total_interest_payable,omitempty"`

	AmountOwning []LoanRepaymentsAmountOwing `json:"amount_owing,omitempty"`
}
